console:
  build: docker/console
  hostname: console-stoerungsmelder
  ports:
    - "127.0.0.1:2223:22"
  volumes:
   - ./:/data
  links:
    - mysql

appserver:
  build: docker/php-app
  volumes:
   - ./:/data
  ports:
    - "8085:80"
  environment:
    - APP_DOCUMENT_ROOT=/data/web
    - VIRTUAL_HOST=stoerungsmelder.r00tmakr0.org
  hostname: appserver-stoerungsmelder
  links:
    - mysql

mysql:
  image: mysql:5
  hostname: mysqlserver-stoerungsmelder
  environment:
    - MYSQL_ROOT_PASSWORD=foobar123
    - MYSQL_DATABASE=stoerungsmelder
    - MYSQL_USER=stoerungsmelder
    - MYSQL_PASSWORD=stoerungsmelder
  volumes:
    - ./var/mysql:/var/lib/mysql
    - ./etc/mysql/conf.d:/etc/mysql/conf.d
