<?php

namespace AppBundle\Entity;

/**
 * MaschineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaschineRepository extends \Doctrine\ORM\EntityRepository
{
}
